#app.yaml
runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: database-hood-mjc-15-a
  CLOUD_SQL_PASSWORD: 123
  CLOUD_SQL_DATABASE_NAME: database-hood-mjc-15-a
  CLOUD_SQL_CONNECTION_NAME: database-hood-mjc-15-a :us-east4:database-hood-mjc-15-a
